backend:
  name: github
  repo: tvtest614-eng/tvtest614-eng.github.io
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Yazılar"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Tarih", name: "date", widget: "datetime" }
      - { label: "Kapak Görseli", name: "image", widget: "image" }
      - { label: "Manşet", name: "featured", widget: "boolean", default: false }
      - { label: "İçerik", name: "body", widget: "markdown" }
